[package]
name = "notification2"
version = "0.1.0"
edition = "2024"

[features]
default = []

[[example]]
name = "test_notification"

[dependencies]
gpui = { version = "0.2.2", features = ["runtime_shaders"] }

[dev-dependencies]
