[package]
name = "flag"
version = "0.1.0"
edition = "2024"

[dependencies]
moka = { workspace = true, features = ["future"] }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
