filter.tag = "^control_v"

[output]
format = "plain"

[next.dev]
prerelease.template = "{pre}.dev.{distance}"
build_metadata.template = "{hash}"

[next.patch]
increment = 1

[next.minor]
increment = 1

[next.major]
increment = 1
