[build]
command = "pnpm -F @hypr/web build && pnpm -F @hypr/docs build && cp -r apps/docs/dist/* apps/web/dist/client/docs/"
publish = "apps/web/dist/client"

[[redirects]]
from = "/docs/*"
to = "/docs/:splat"
status = 200
