app = 'hyprnote-restate'
primary_region = 'sjc'
kill_signal = 'SIGTERM'
kill_timeout = 30
swap_size_mb = 512

[deploy]
strategy = "bluegreen"

[env]
PORT = "9080"

[http_service]
processes = ['app']
internal_port = 9080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1

[http_service.concurrency]
type = "connections"
hard_limit = 200
soft_limit = 150

[[vm]]
processes = ['app']
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
