# fly.toml app configuration file generated for hyprnote-restate on 2026-02-15T13:17:04+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hyprnote-restate'
primary_region = 'sjc'
kill_signal = 'SIGTERM'
kill_timeout = '30s'
swap_size_mb = 512

[env]
PORT = '8080'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[http_service.http_options]
h2_backend = true

[http_service.concurrency]
type = 'connections'
hard_limit = 200
soft_limit = 150

[[vm]]
memory = '1gb'
cpus = 1
memory_mb = 1024
processes = ['app']
