# https://github.com/restatedev/cloudflare-workers-template/blob/main/wrangler.toml

name = "hypr-restate"
main = "./src/index.ts"
preview_urls = true

compatibility_date = "2025-09-23"
compatibility_flags = ["nodejs_compat"]
