[package]
name = "posthog"
version = "0.1.0"
edition = "2024"

[dependencies]
posthog-core = { git = "https://github.com/yujonglee/posthog-rs", package = "posthog-core", rev = "1779042" }
posthog-rs = { git = "https://github.com/yujonglee/posthog-rs", package = "async-posthog", rev = "1779042" }

chrono = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
