[package]
name = "extensions-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
deno_core = "0.338"

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "sync"] }
tracing = { workspace = true }
