[package]
name = "vvad"
version = "0.1.0"
edition = "2021"
links = "vvad"

[target.'cfg(all(target_os = "macos", target_arch = "aarch64"))'.dependencies]
hypr-am2 = { workspace = true }

[target.'cfg(all(target_os = "macos", target_arch = "aarch64"))'.build-dependencies]
swift-rs = { workspace = true, features = ["build"] }

[target.'cfg(not(all(target_os = "macos", target_arch = "aarch64")))'.dependencies]
earshot = { workspace = true }
