[package]
name = "vvad"
version = "0.1.0"
edition = "2021"

[target.'cfg(all(target_os = "macos", target_arch = "aarch64"))'.dependencies]
hypr-am2 = { workspace = true }

[target.'cfg(not(all(target_os = "macos", target_arch = "aarch64")))'.dependencies]
earshot = { workspace = true }
