[package]
name = "llm-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }

axum = { workspace = true }
bytes = { workspace = true }
futures-util = { workspace = true }
reqwest = { workspace = true, features = ["json", "stream"] }
tokio = { workspace = true, features = ["rt-multi-thread", "time", "sync", "macros"] }
tracing = { workspace = true }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
