[package]
name = "askama-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = { workspace = true }
askama_parser = { workspace = true }
chrono = { workspace = true }
isolang = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
