[package]
name = "desktop"
version = "0.0.0"
authors = ["you"]
edition = "2021"
description = "Hyprnote desktop App"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "hyprnote_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { workspace = true, features = [] }

[dependencies]
tauri = { workspace = true, features = ["specta", "macos-private-api", "protocol-asset"] }

tauri-plugin-analytics = { workspace = true }
tauri-plugin-auth = { workspace = true }
tauri-plugin-autostart = { workspace = true }
tauri-plugin-cli = { workspace = true }
tauri-plugin-cli2 = { workspace = true }
tauri-plugin-clipboard-manager = { workspace = true }
tauri-plugin-db2 = { workspace = true }
tauri-plugin-deep-link = { workspace = true }
tauri-plugin-deeplink2 = { workspace = true }
tauri-plugin-detect = { workspace = true }
tauri-plugin-dialog = { workspace = true }
tauri-plugin-fs = { workspace = true }
tauri-plugin-hooks = { workspace = true }
tauri-plugin-http = { workspace = true }
tauri-plugin-importer = { workspace = true }
tauri-plugin-listener = { workspace = true }
tauri-plugin-listener2 = { workspace = true }
tauri-plugin-local-stt = { workspace = true }
tauri-plugin-misc = { workspace = true }
tauri-plugin-notification = { workspace = true }
tauri-plugin-opener = { workspace = true }
tauri-plugin-os = { workspace = true }
tauri-plugin-permissions = { workspace = true }
tauri-plugin-prevent-default = { workspace = true }
tauri-plugin-process = { workspace = true }
tauri-plugin-sentry = { workspace = true }
tauri-plugin-shell = { workspace = true }
tauri-plugin-single-instance = { workspace = true }
tauri-plugin-store = { workspace = true }
tauri-plugin-store2 = { workspace = true }
tauri-plugin-template = { workspace = true }
tauri-plugin-tracing = { workspace = true }
tauri-plugin-tray = { workspace = true }
tauri-plugin-updater = { workspace = true }
tauri-plugin-windows = { workspace = true }

specta = { workspace = true }
specta-typescript = { workspace = true }
tauri-specta = { workspace = true, features = ["derive", "typescript"] }

sentry = { workspace = true, features = ["tracing"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
strum = { workspace = true, features = ["derive"] }
tracing = { workspace = true }

ractor = { workspace = true }
ractor-supervisor = { workspace = true }

tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

[features]
devtools = ["tauri/devtools"]
