[package]
name = "device-events"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = { workspace = true }
hypr-device-heuristic = { workspace = true }

[target."cfg(target_os = \"macos\")".dependencies]
cidre = { workspace = true }

[target."cfg(target_os = \"linux\")".dependencies]
libpulse-binding = "2.30"
