[env]
GGML_NATIVE = "OFF"
GGML_CPU_NATIVE = "0"
CMAKE_C_FLAGS = "-mcpu=apple-m1"
CMAKE_CXX_FLAGS = "-mcpu=apple-m1"
CC = "clang"
CXX = "clang++"
CFLAGS = "-mcpu=apple-m1"
CXXFLAGS = "-mcpu=apple-m1"
CMAKE_OSX_ARCHITECTURES = "arm64"
CMAKE_SYSTEM_PROCESSOR = "aarch64"
CMAKE_HOST_SYSTEM_PROCESSOR = "aarch64"

[target.aarch64-apple-darwin]
rustflags = ["-C", "target-cpu=apple-m1"]

[build]
target = "aarch64-apple-darwin" 