[package]
name = "template2"
version = "0.1.0"
edition = "2024"

[dependencies]
hypr-template-assets = { workspace = true }

askama = { workspace = true }
serde = { workspace = true, features = ["derive"] }
specta = { workspace = true, features = ["derive"] }
