[package]
name = "template-app"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = { workspace = true }
chrono = { workspace = true }
hypr-askama-utils = { workspace = true }
isolang = { workspace = true }
serde = { workspace = true, features = ["derive"] }
specta = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
