[package]
name = "template-eval"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = { workspace = true }
serde = { workspace = true, features = ["derive"] }
specta = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }

[dev-dependencies]
hypr-askama-utils = { workspace = true }
insta = { workspace = true }
