[package]
name = "notification-linux"
version = "0.1.0"
edition = "2021"

[features]
linux-examples = []

[[example]]
name = "test_notification"
required-features = ["linux-examples"]

[dependencies]
glib = "0.20"
gtk4 = "0.9"
hypr-notification-interface = { workspace = true }
indexmap = "2.6"
once_cell = "1.20"
open = "5.3"
uuid = { version = "1.11", features = ["v4"] }

[target.'cfg(target_os = "linux")'.dev-dependencies]
tokio = { workspace = true }
