[package]
name = "notification-linux"
version = "0.1.0"
edition = "2021"

[features]
linux-examples = []

[[example]]
name = "test_notification"
required-features = ["linux-examples"]

[dev-dependencies]
tokio = { workspace = true }

[dependencies]
hypr-notification-interface = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
glib = "0.21"
gtk4 = "0.10"
once_cell = { workspace = true }
open = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
