[package]
name = "notch"
version = "0.1.0"
edition = "2021"

[features]
macos-examples = []

[[example]]
name = "test_notch"
required-features = ["macos-examples"]

[target.'cfg(target_os = "macos")'.build-dependencies]
swift-rs = { workspace = true, features = ["build"] }

[target.'cfg(target_os = "macos")'.dependencies]
swift-rs = { workspace = true }

[target.'cfg(target_os = "macos")'.dev-dependencies]
objc2 = { workspace = true }
objc2-app-kit = { workspace = true }
objc2-foundation = { workspace = true }
