[package]
name = "owhisper-providers"
version = "0.0.1"
edition = "2024"

[dependencies]
serde_json = { workspace = true }
strum = { workspace = true, features = ["derive"] }
url = { workspace = true }
