[package]
name = "openai"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = { workspace = true }
url = { workspace = true }

async-openai = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
reqwest-middleware = { workspace = true, features = ["json"] }
reqwest-retry = { workspace = true }
