# https://docs.netlify.com/build/configure-builds/overview/#definitions
# Base directory is set to "apps/storybook" in the Netlify UI
# Publish path is relative to the base directory
[build]
command = "pnpm -F @hypr/storybook build"
publish = "storybook-static"

[build.environment]
NODE_VERSION = "22"
