[package]
name = "template-support"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = { workspace = true }
serde = { workspace = true, features = ["derive"] }
specta = { workspace = true, features = ["derive"] }
utoipa = { workspace = true }
