[package]
name = "restate-stt-types"
version = "0.1.0"
edition = "2024"

[features]
utoipa = ["dep:utoipa"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

utoipa = { workspace = true, optional = true }
