[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
mac_address2 = "2.0.2"
machine-uid = "0.5.4"
sysinfo = { workspace = true }
tokio = { workspace = true, features = ["time"] }
