[package]
name = "vad-ext"
version = "0.1.0"
edition = "2021"

[target.'cfg(all(target_os = "macos", target_arch = "aarch64"))'.build-dependencies]
swift-rs = { workspace = true, features = ["build"] }

[dev-dependencies]
hound = { workspace = true }
hypr-data = { workspace = true }
rodio = { workspace = true }

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }

hypr-audio-utils = { workspace = true }
hypr-vad3 = { workspace = true }
hypr-vvad = { workspace = true }
kalosm-sound = { workspace = true, default-features = false }
silero-rs = { workspace = true }

futures-util = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing = { workspace = true }
