[package]
name = "restate-stt"
version = "0.1.0"
edition = "2024"

[dependencies]
hypr-restate-stt-types = { workspace = true }
restate-sdk = "0.7.0"

chrono = { workspace = true, features = ["serde"] }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
soniox = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
urlencoding = { workspace = true }
