[package]
name = "db-core"
version = "0.1.0"
edition = "2024"

[dependencies]
libsql = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[features]
encryption = ["libsql/encryption"]
