# https://docs.netlify.com/build/configure-builds/overview/#definitions
# We must set package="apps/howto" in the UI
[build]
command = "pnpm -F @hypr/howto build"
publish = "apps/howto/dist"

[build.environment]
NODE_VERSION = "22"
