[package]
name = "mlx"
version = "0.1.0"
edition = "2024"

[target.'cfg(target_os = "macos")'.build-dependencies]
swift-rs = { workspace = true, features = ["build"] }

[target.'cfg(target_os = "macos")'.dependencies]
swift-rs = { workspace = true }

[dev-dependencies]
hypr-data = { workspace = true }
