[package]
name = "mcp"
version = "0.1.0"
edition = "2024"

[dependencies]
hypr-api-auth = { workspace = true }

askama = { workspace = true }
axum = { workspace = true }
rmcp = { workspace = true, features = ["server", "transport-streamable-http-server"] }
