# fly.toml app configuration file generated for hyprnote-api on 2025-11-15T10:28:09+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hyprnote-api'
primary_region = 'sjc'
kill_signal = 'SIGTERM'
kill_timeout = 30
swap_size_mb = 512

[build]
dockerfile = "Dockerfile"

[deploy]
strategy = "bluegreen"

[env]
BUN_ENV = "production"
PORT = "8787"

[http_service]
processes = ['app']
internal_port = 8787
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1

[http_service.concurrency]
type = "connections"
hard_limit = 200
soft_limit = 150

[[http_service.checks]]
grace_period = "20s"
interval = "15s"
method = "GET"
path = "/health"
protocol = "http"
timeout = "4s"

[[vm]]
processes = ['app']
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
