name: openstatus

on:
  push:
    branches:
      - main
    paths:
      - openstatus.yaml
      - .github/workflows/openstatus.yaml
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install OpenStatus CLI
        run: curl -sSL instl.sh/openstatushq/cli/linux | bash

      - name: Apply monitors
        env:
          OPENSTATUS_API_TOKEN: ${{ secrets.OPENSTATUS_API_TOKEN }}
        run: openstatus monitors apply --auto-accept
