on:
  workflow_dispatch:
  push:
    paths:
      - "apps/slack-internal/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: depot-ubuntu-24.04-8
    timeout-minutes: 60
    concurrency: slack-internal-fly-deploy
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --config apps/slack-internal/fly.toml --remote-only --build-arg GIT_SHA=${{ github.sha }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
