name: web_ci

# https://github.com/tauri-apps/tauri-action/blob/3013cac/examples/test-build-only.yml
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - apps/web/**
      - packages/**
  pull_request:
    branches-ignore:
      - "**/graphite-base/**"
    paths:
      - apps/web/**
      - packages/**
jobs:
  optimize_ci:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check_skip.outputs.skip }}
    steps:
      - uses: actions/checkout@v4
      - id: check_skip
        uses: ./.github/actions/graphite_optimizer
        with:
          graphite_token: ${{ secrets.GRAPHITE_TOKEN }}

  ci:
    needs: optimize_ci
    if: needs.optimize_ci.outputs.skip == 'false'
    runs-on: depot-ubuntu-24.04-4
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm_install
      - uses: denoland/setup-deno@v2
      - run: pnpm -F ui build
      - run: pnpm -F web typecheck
      - uses: ./.github/actions/wait-for-netlify-preview
        if: github.event_name == 'pull_request'
      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: echo "BASE_URL=https://char.netlify.app" >> "$GITHUB_ENV"
      - run: pnpm exec playwright install --with-deps chromium
        working-directory: apps/web
      - run: pnpm -F web test
