[package]
name = "supabase-auth"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
specta = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }

base64 = { workspace = true }
jsonwebtoken = { workspace = true }

reqwest = { workspace = true, features = ["json"] }
tokio = { workspace = true }
